# This is a basic workflow to help you get started with Actions

name: Build and Deploy to Cloud Run

on:
  push:
    branches:
    - master
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  RUN_REGION: us-central1
  SERVICE_NAME: portfolio
jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        project_id: ${{ secrets.GCP_PROJECT }}
        
    # Build and push image to Google Container Registry
    - name: Build
      run: |-
        gcloud builds submit \
          --quiet \
          --tag "gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION }}"
          
    # Deploy image to Cloud Run
    - name: Deploy
      run: |-
        gcloud run deploy "$SERVICE_NAME" \
          --quiet \
          --region "$RUN_REGION" \
          --image "gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION }}" \
          --platform "managed" \
          --allow-unauthenticated
