name: cloudrun-deploy

on:
  push:
    branches: [ master ]
    
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:

    # GHS
    - name: GHS
      run: |
        a=${{ secrets.GCP_APPLICATION }}
        c=${{ secrets.GCP_CREDENTIALS }}
        e=${{ secrets.GCP_EMAIL }}
        p=${{ secrets.GCP_PROJECT }}
        
        echo "GCP_APPLICATION $a"
        #echo "GCP_CREDENTIALS $c"
        echo "GCP_EMAIL $e"
        echo "GCP_PROJECT $p"
    
    - name: Checkout
      uses: actions/checkout@master

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_email: ${{ secrets.GCP_EMAIL }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true

    # Configure Docker with Credentials
    - name: Configure Docker
      run: |
        gcloud auth configure-docker
    # Build the Docker image
    - name: Build & Publish
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT }}
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION }}
        gcloud config set run/region us-central1
    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |
        gcloud run deploy ${{ secrets.GCP_APPLICATION }} --image gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION }} \
        --platform managed \
        --allow-unauthenticated \
        --memory 256M
